### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by gamtiq** [commoncrawl/cc-pyspark#23]
There are the following broken links in `README.md`:
* see the project [cc-webgraph](https://github.com/commoncrawl/cc-pyspark/blob/master/commoncrawl/cc-webgraph)
* see also [cc-index-table](https://github.com/commoncrawl/cc-pyspark/blob/master/commoncrawl/cc-index-table)

**Comment by sebastian-nagel** [comment]
Thanks, @gamtiq. The links are fixed now.
