### ISSUE TITLE
Use SparkSession instead of SQLContext

### ISSUE THREAD

**Issue by sebastian-nagel** [commoncrawl/cc-pyspark#24]
"As of Spark 2.0, [SQLContext] is replaced by SparkSession." (see [SQLContext](https://spark.apache.org/docs/3.0.1/api/java/org/apache/spark/sql/SQLContext.html)).
- replacing SQLContext by [SparkSession](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.SparkSession) might simplify the code as the session also holds the SparkContext object
- the current session can be accessed from the static method [SparkSession.getActiveSession()](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.SparkSession.getActiveSession) (since 2.2.0)

**Comment by m3et** [comment]
Hey, 

I'm running on a managed AWS Sagemaker Spark cluster, I did just fetched this commit and others to enable access to warc through HTTP.

I used to use the sparkContext and now I can see there was an update to use sparkSession, it all used to work  but now I recive this error:

` for k, v in iterator:
  File "/tmp/localPyFiles-155a55ad-b2de-498e-b546-921969ce41a0/sparkcc.py", line 351, in process_warcs
    stream = self.fetch_warc(uri, self.args.input_base_url)
  File "/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1650441743930_0001/container_1650441743930_0001_01_000002/__pyfiles__/sparkcc.py", line 304, in fetch_warc
    self.get_logger().info('Fetching {}'.format(uri))
  File "/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1650441743930_0001/container_1650441743930_0001_01_000002/__pyfiles__/sparkcc.py", line 170, in get_logger
    session = SparkSession.getActiveSession()
AttributeError: type object 'SparkSession' has no attribute 'getActiveSession'`

When I remove  this line from 'get_logger' function:

`def get_logger(self, session=None):
    """Get logger from SparkSession or (if None) from logging module"""
    if session:
        return session._jvm.org.apache.log4j.LogManager \
                    .getLogger(self.name)
    return logging.getLogger(self.name)`

The program run as expected but there is no logging from the workers.

I guess the underling problem is that the works doesn't hold the sparkSession object so when trying to log we receive this error, but I'm not sure bout that.

If anyone has encounter such problem please let me know., as well as any additional information needed

**Comment by sebastian-nagel** [comment]
Hi @m3et, which version of Spark do you use? The method [getActiveSession()](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.SparkSession.getActiveSession.html) was introduced with Spark 3.0.0 - sorry, I've overseen this backward-incompatibility issue when switching to use only SparkSession and no SQLContext. And yes, it's safe to remove the line or put in a try-clause and do nothing if it fails. The fall-back is to use the Python logging. I'll try to reproduce the issue and will update the code. Thanks, @m3et!

**Comment by sebastian-nagel** [comment]
Hi @m3et, I was able to reproduce the problem using Spark 2.4.8 together with Python 2.7 - the error is now fixed, see 66dba9a.

**Comment by m3et** [comment]
Great! Thank you.

**Comment by sebastian-nagel** [comment]
Implemented by #25
