### ISSUE TITLE
Class org.apache.hadoop.fs.s3a.S3AFileSystem not found

### ISSUE THREAD

**Issue by BrownXing** [commoncrawl/cc-pyspark#30]
I met this error when running cc_index_word_count.py, it is raise when conducting this line:

`./sparkcc.py, line 354`
`df = parquet_reader.load(table_path)`

**Comment by sebastian-nagel** [comment]
Please, see the [README "Installation of S3 Support Libraries"](https://github.com/commoncrawl/cc-pyspark#installation-of-s3-support-libraries).

**Comment by BrownXing** [comment]
> Please see the [README "Installation of S3 Support Libraries"](https://github.com/commoncrawl/cc-pyspark#installation-of-s3-support-libraries). Let me know if this does not work. Thanks!

Thanks ! I have solved this problem by adding the s3 support.
