### ISSUE TITLE
Bad Substitution

### ISSUE THREAD

**Issue by swetepete** [commoncrawl/cc-pyspark#33]
> Alternatively, running get-data.sh downloads the sample data.

```
% ./get-data.sh
./get-data.sh: line 20: Downloading Common Crawl paths listings (${data_type^^} files of $CRAWL)...: bad substitution
```

Could anyone explain why my attempts at running this script result in this message?

Thank you

**Comment by sebastian-nagel** [comment]
See #31 - but I hear you and merge #31 to make the script POSIX-compliant.

**Comment by sebastian-nagel** [comment]
Hi @swetepete, please update. The script get-data.sh is now POSIX-compliant and should work with most shells. This should also fix this issue.

**Comment by swetepete** [comment]
Thanks very much
